'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight,Wifi,ScanLine,SlidersHorizontal,ShieldCheck,Camera,Monitor} from 'lucide-react';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {DownloadActions,HelpButton} from './product-actions';
import CameraApp from './camera-app';
import {GITHUB,DEVELOPER,VERSION} from '@/lib/product';
export const faqs=[
 ['Это действительно бесплатная альтернатива iVcam?','Да. VCam можно использовать бесплатно: без рекламы, водяного знака и платного доступа к настройкам. Это независимый проект, не связанный с iVcam или его разработчиком.'],
 ['Нужно что-то устанавливать на iPhone?','Нет. Приложение устанавливается только на Windows. На iPhone открой QR-ссылку в Safari или введи код на сайте и разреши доступ к камере.'],
 ['Какие устройства и программы подходят?','Приёмник работает на 64-битной Windows 10 и 11. На iPhone используй Safari, на Android — Chrome. Видеокамера VCam доступна приложениям с поддержкой DirectShow, например OBS и Zoom. Доступные режимы зависят от устройства и браузера; все модели телефонов ещё не проверены.'],
 ['Будут 4K, 60 FPS и все объективы?','VCam проверяет режимы камеры и показывает только доступные сочетания. 4K и 60 FPS зависят от телефона, браузера, сети и мощности компьютера. Safari может не предоставлять все объективы и ручные настройки штатной камеры.'],
 ['Куда передаётся видео?','Напрямую между телефоном и компьютером через зашифрованное WebRTC-соединение. Сервер помогает устройствам встретиться, но не получает и не хранит видеопоток. Для подключения нужен интернет, для стабильной работы — одна сеть Wi-Fi без изоляции устройств.'],
 ['Что делать, если QR не открывается?','Открой VCam на компьютере и создай подключение. На телефоне нажми «Подключить телефон» на этом сайте и введи восемь символов кода. Код одноразовый и действует десять минут.'],
 ['Можно свернуть Safari или передавать звук?','Оставь страницу камеры открытой и телефон разблокированным. При уходе в фон система может остановить камеру. Сейчас VCam передаёт только видео, без микрофона.'],
 ['Почему Windows предупреждает об издателе?','Установщик пока без цифровой подписи издателя. Скачивай его только из официальных Releases этого репозитория. Регистрация виртуальной камеры требует прав администратора.']
];
export default function SiteHome(){
 const [pairing,setPairing]=useState(false);
 useEffect(()=>{const update=()=>setPairing(new URLSearchParams(location.hash.slice(1)).has('room')||new URLSearchParams(location.search).has('camera'));update();window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update)},[]);
 if(pairing)return <CameraApp phoneMode/>;
 return <div className="landing"><a className="skip-link" href="#main">К содержимому</a><header className="site-nav"><a className="brand" href="/" aria-label="VCam — главная"><img src="/brand/icon-64.png" width="32" height="32" alt=""/>VCam</a><nav aria-label="Навигация"><a href="#features">Возможности</a><a href="#faq">Вопросы</a><a href={GITHUB} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15}/></a></nav><a href="/connect" className="nav-connect">Подключить телефон<ArrowRight size={16}/></a></header>
 <main id="main"><section className="landing-hero"><p className="eyebrow">ТВОЙ ТЕЛЕФОН. ТВОЯ ВЕБ-КАМЕРА.</p><h1>Камера уже у тебя.<br/><span>Осталось подключить.</span></h1><p className="hero-description">Камера телефона — на твоём Windows.<br/>Бесплатно. Без рекламы. Без приложения на телефоне.</p><div className="hero-actions" id="download"><DownloadActions/><a className="github-button" href={GITHUB} target="_blank" rel="noreferrer"><img src="/brands/github.svg" width="20" height="20" alt=""/>GitHub</a></div><div className="hero-meta"><span>Windows 10 / 11 · v{VERSION} beta</span><HelpButton label/></div><figure className="hero-image"><img src="/images/vcam-meadow.webp" width="1536" height="1024" fetchPriority="high" alt="Мокап VCam: iPhone и ноутбук показывают один видеопоток с розовыми цветами"/></figure></section>
 <section className="compatibility" aria-label="Устройства и приложения"><p>На телефоне — браузер.<br className="mobile-break"/> На компьютере — привычные приложения.</p><div className="brand-strip">{[['windows','Windows'],['apple','iPhone'],['safari','Safari'],['android','Android'],['googlechrome','Chrome'],['obsstudio','OBS'],['zoom','Zoom']].map(([icon,label])=><span key={icon}><img src={`/brands/${icon}.svg`} width="26" height="26" alt=""/>{label}</span>)}</div><small>Возможности зависят от устройства и браузера. Совместимые приложения принимают DirectShow-камеры.</small></section>
 <section className="feature-section" id="features"><div className="section-heading"><p className="eyebrow">МЕНЬШЕ НАСТРОЙКИ. БОЛЬШЕ КАЧЕСТВА.</p><h2>Хорошая камера.<br/><span>Без лишней покупки.</span></h2><p>Для звонков, стримов и записи видео.<br/>Камера телефона, управление с компьютера.</p></div><div className="feature-grid"><article><ScanLine/><h3>Наведи. Разреши. Готово.</h3><p>QR в приложении Windows открывает камеру на телефоне. Не получилось — введи короткий код.</p><a href="/connect">Подключить телефон <ArrowRight size={17}/></a></article><article><SlidersHorizontal/><h3>Всё под рукой.</h3><p>Переключай камеры, меняй качество, зум и поворот прямо с компьютера. Только доступные устройству настройки.</p><span className="feature-value">1080p <span>/ до 4K*</span></span></article><article><Wifi/><h3>Короткий путь до кадра.</h3><p>Прямое соединение по Wi-Fi. Видео не путешествует через облачный сервер.</p><span className="feature-value">Телефон <ArrowRight size={20}/> Windows</span></article><article><ShieldCheck/><h3>Только твоё видео.</h3><p>Зашифрованный поток, одноразовое подключение. Без записи на сервере, рекламы и водяных знаков.</p><span className="feature-value">0 ₽ <span>за все функции</span></span></article></div><p className="quality-footnote">* Разрешение и FPS проверяются на устройстве. Скорость подключения и задержка зависят от сети. Фактические параметры потока видны в VCam.</p></section>
 <section className="quiet-section"><div><p className="eyebrow">ПРОСТРАНСТВО ДЛЯ ТЕБЯ</p><h2>Ты в кадре.<br/><span>Остальное — проще.</span></h2><p>Телефон на подставке. VCam на компьютере.<br/>И привычная кнопка «Включить камеру» в звонке.</p><HelpButton label/></div><figure><img src="/images/vcam-studio.webp" width="1536" height="1024" loading="lazy" alt="Мокап рабочего места VCam: телефон и ноутбук среди папоротников и белых цветов"/></figure></section>
 <section className="faq-section" id="faq"><h2>Несколько<br/><span>хороших вопросов.</span></h2><Accordion type="single" collapsible>{faqs.map(([q,a],i)=><AccordionItem value={String(i)} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></section>
 <section className="last-call"><Camera size={34}/><h2>Дай камере телефона<br/><span>ещё одну роль.</span></h2><DownloadActions/><a href="/connect" className="simple-link">Приложение уже установлено? Подключить телефон <ArrowRight size={16}/></a></section>
 <section className="developer-section"><p>Вопрос, идея или просто привет?</p><a href={DEVELOPER} target="_blank" rel="noreferrer">Напиши разработчику.<ArrowUpRight/></a><span>prodbyeddy.com</span></section></main><footer className="site-footer"><span>VCam · Бесплатно и без рекламы</span><a href={GITHUB} target="_blank" rel="noreferrer">Исходный код <ArrowUpRight size={14}/></a><span>Сделано EDDY</span></footer></div>;
}
