import {Check,Monitor,ScanLine,Video,Wifi,ShieldCheck,SlidersHorizontal,Smartphone,ArrowUpRight} from 'lucide-react';
import {SiteHeader,SiteFooter} from '@/components/site-chrome';
import {DownloadActions,HelpButton} from '@/components/product-actions';
import {DownloadCount} from '@/components/download-count';
import {applicationSchema} from '@/lib/seo';
import {faqsEn} from '@/content/faq-en';
import {GITHUB,DEVELOPER} from '@/lib/product';
export default function Home(){return <div className="landing"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(applicationSchema('en')).replace(/</g,'\\u003c')}}/><SiteHeader locale="en" path="/en"/><main id="main">
 <section className="landing-hero"><h1>Your phone. A free<br/><span>webcam for Windows.</span></h1><p className="hero-description">VCam turns your iPhone or Android phone into a webcam for OBS, Zoom and video calls. Install VCam on Windows; your phone connects through its browser over Wi-Fi.</p><div className="hero-terms"><span><Check size={16}/>Free</span><span><Check size={16}/>No ads</span><span><Check size={16}/>No watermark</span></div><div className="hero-actions"><DownloadActions locale="en"/></div><a className="download-details" href="/en/download">Windows requirements, version and direct download</a><div className="hero-meta"><DownloadCount locale="en"/><HelpButton locale="en" label/></div><figure className="hero-image"><img src="/images/vcam-office.webp" width="1672" height="941" fetchPriority="high" alt="Illustration of a phone used as a webcam beside a Windows laptop"/><figcaption className="hero-specs"><div><strong><small>up to</small> 4K</strong><span>Video resolution</span></div><div><strong><small>up to</small> 60 <small>FPS</small></strong><span>Frame rate</span></div><div><Wifi size={25}/><span>Local Wi-Fi connection</span></div></figcaption></figure><p className="quality-footnote">Available resolution, frame rate and controls depend on your phone and browser. VCam checks supported modes.</p></section>
 <section className="compatibility" aria-label="Devices and applications"><div className="brand-strip">{[['windows','Windows'],['apple','iPhone'],['safari','Safari'],['android','Android'],['googlechrome','Chrome'],['obsstudio','OBS'],['zoom','Zoom']].map(([icon,label])=><span key={icon}><img src={`/brands/${icon}.svg`} width="26" height="26" alt=""/>{label}</span>)}</div><p>Safari on iPhone. Chrome on Android.<br/>A DirectShow virtual camera on Windows 10/11.</p></section>
 <section className="feature-section" id="features"><div className="section-heading"><h2>All features are free</h2><p>No subscription, ads or paid camera settings.</p></div><div className="feature-grid"><article className="free-feature"><div className="free-price">0 <span>$</span></div><h3>No payment needed</h3><ul>{['All available video quality settings','No software time limit','No watermark','No advertising'].map(t=><li key={t}><Check/>{t}</li>)}</ul><a href={GITHUB}>Source code on GitHub<ArrowUpRight size={17}/></a></article><article className="controls-feature"><SlidersHorizontal/><h3>Camera controls<br/>on your computer</h3><p>Change cameras, zoom, resolution and frame rate. Rotate or mirror the video. Available controls depend on the phone browser.</p><div className="control-labels"><span>Zoom</span><span>Rotation</span><span>Quality</span><span>Lenses</span></div></article><article className="connection-feature"><Smartphone/><h3>No phone app</h3><p>Scan the QR code or enter the one-time code, open the browser camera and allow access.</p><a href="/en/connect">Enter a connection code →</a></article><article className="privacy-feature"><ShieldCheck/><h3>Direct encrypted video</h3><p>The video stream goes directly from your phone to your computer. VCam does not record or store your video on its server.</p><a href="/en/about">How VCam works →</a></article></div></section>
 <section className="setup-section" id="setup"><div className="section-heading"><h2>How to use your phone as a webcam</h2><p>Connect the phone and computer to the same local Wi-Fi network.</p></div><div className="setup-steps">{[{Icon:Monitor,title:'Install VCam on Windows',text:'Open the receiver and click Show QR code. It displays a QR code and a one-time connection code.'},{Icon:ScanLine,title:'Open the camera on your phone',text:'Scan the QR code, open the link and allow camera access in Safari or Chrome. Keep the page open and the phone unlocked.'},{Icon:Video,title:'Select VCam in your application',text:'Choose VCam in the camera settings of OBS, Zoom or another compatible Windows application. Select a separate microphone for audio.'}].map(({Icon,title,text},i)=><article key={title}><div className="setup-step-top"><span>{i+1}</span><Icon size={26}/></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="faq-section" id="faq"><h2>Questions<br/>and answers</h2><div className="native-faq">{faqsEn.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
 <section className="home-blog"><div><h2>Phone webcam guides</h2><a href="/en/guides">All guides ↗</a></div><div className="home-blog-grid">{[['iphone-webcam-windows','iphone-veb-kamera-windows','Use iPhone as a Windows webcam'],['android-webcam-windows','android-veb-kamera-windows','Use Android as a Windows webcam'],['phone-camera-obs','telefon-kamera-obs','Add a phone camera to OBS']].map(([slug,image,title])=><a key={slug} href={`/en/guides/${slug}`}><img src={`/images/blog/${image}.webp`} width="1600" height="900" loading="lazy" alt=""/><h3>{title}</h3></a>)}</div></section>
 <section className="last-call"><img src="/brand/icon-64.png" width="54" height="54" alt=""/><h2>Download VCam<br/>for Windows</h2><DownloadActions locale="en"/><a className="simple-link" href="/en/download">Version and system requirements →</a></section><section className="developer-section"><a href={DEVELOPER}>Contact the developer<ArrowUpRight/></a><span>prodbyeddy.com</span></section></main><SiteFooter locale="en"/></div>}
