import {notFound} from 'next/navigation';
import {guidesEn,getGuide} from '@/content/guides-en';
import {BlogContent} from '@/components/blog-content';
import {SiteHeader,SiteFooter} from '@/components/site-chrome';
import {pageMetadata,updated} from '@/lib/seo';
import {SITE,DEVELOPER} from '@/lib/product';
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return guidesEn.map(g=>({slug:g.slug}))}
export async function generateMetadata({params}:Props){const g=getGuide((await params).slug);if(!g)return {title:'Guide not found — VCam',robots:{index:false,follow:true}};return {...pageMetadata('en','/en/guides/'+g.slug,g.title+' — VCam',g.description),openGraph:{type:'article',locale:'en_US',url:'/en/guides/'+g.slug,title:g.title,description:g.description,publishedTime:updated+'T00:00:00+07:00',modifiedTime:updated+'T00:00:00+07:00',authors:[DEVELOPER],images:[{url:'/images/blog/'+g.ru+'.webp',width:1600,height:900,alt:'Illustration for a phone webcam guide'}]}}}
export default async function Page({params}:Props){const g=getGuide((await params).slug);if(!g)notFound();const url=SITE+'/en/guides/'+g.slug,schema={'@context':'https://schema.org','@graph':[{'@type':'TechArticle','@id':url+'#article',headline:g.title,description:g.description,image:SITE+'/images/blog/'+g.ru+'.webp',datePublished:updated+'T00:00:00+07:00',dateModified:updated+'T00:00:00+07:00',inLanguage:'en',isAccessibleForFree:true,mainEntityOfPage:url,author:{'@type':'Person',name:'EDDY',url:DEVELOPER},about:{'@id':SITE+'/#application'}},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'VCam',item:SITE+'/en'},{'@type':'ListItem',position:2,name:'Guides',item:SITE+'/en/guides'},{'@type':'ListItem',position:3,name:g.title,item:url}]}]};return <><SiteHeader locale="en" path={'/en/guides/'+g.slug}/><main id="main" className="seo-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/><nav className="seo-breadcrumb" aria-label="Breadcrumb"><a href="/en">VCam</a><span>/</span><a href="/en/guides">Guides</a></nav><h1>{g.title}</h1><p className="lede">{g.description}</p><p className="seo-note"><a href={DEVELOPER}>EDDY · VCam developer</a> · <time dateTime={updated}>October 2, 2026</time></p><BlogContent body={g.body}/><h2>Try VCam</h2><p>Free, no ads or watermark. Install it on Windows and connect your phone through its browser.</p><a className="action-primary" href="/en/download">Download and system requirements</a><h2>More guides</h2><div className="seo-related">{guidesEn.filter(a=>a.slug!==g.slug).map(a=><a key={a.slug} href={'/en/guides/'+a.slug}>{a.title}</a>)}</div></main><SiteFooter locale="en"/></>}
