export const faqsEn=[
 ['What is VCam?','VCam is a free Windows application that turns an iPhone or Android phone into a wireless webcam. Install the receiver on Windows, open the phone camera in Safari or Chrome, and select VCam in OBS, Zoom or another application that accepts DirectShow cameras.'],
 ['Is VCam really free?','Yes. All implemented features are free, with no ads, subscription, watermark or software time limit. The source code is published on GitHub. VCam is an independent project and is not affiliated with iVcam, DroidCam, Camo or Elgato.'],
 ['Do I need to install an app on my phone?','No. Use Safari on iPhone or Chrome on Android. Open the QR-code link from the Windows app and allow camera access. You can also enter the eight-character connection code on the Connect phone page. Each code is valid for ten minutes and can be used once.'],
 ['Which computers and applications are supported?','The receiver requires 64-bit Windows 10 or Windows 11 and administrator permission during installation. It provides a DirectShow virtual camera for compatible 32-bit and 64-bit applications, including OBS and Zoom. There is currently no receiver for macOS or Linux. Compatibility with every phone and application has not been tested.'],
 ['Does it support 4K and 60 FPS?','VCam probes the camera and offers the resolution and frame-rate combinations it confirms. Up to 4K and 60 FPS are possible on supported devices, but 4K at 60 FPS is not guaranteed. Camera lenses and manual controls depend on the phone and browser.'],
 ['Does VCam send my video to a server?','Video travels directly between the phone and computer over an encrypted WebRTC connection. VCam does not record or store it on the server. The server serves the website and helps pair the devices. Both devices need the same local Wi-Fi network without client isolation; an internet connection is needed to open the site and pair.'],
 ['Can I use it through USB or transmit phone audio?','The current version uses local Wi-Fi and transmits video only. It has no dedicated USB connection mode. Choose your computer microphone or a separate microphone for calls and recordings.'],
 ['Can I lock the phone or minimize the browser?','Keep the camera page open and the phone screen unlocked. The phone operating system can pause the camera when the browser moves into the background. You can minimize the Windows receiver while it is streaming.'],
 ['Why does Windows show a publisher warning?','The beta installer is not yet signed with a publisher certificate. Download it only from the official prodbyEDDY/vcam GitHub Releases page. Administrator permission is needed to register the virtual camera.']
] as const;
