import {SiteHeader,SiteFooter} from '@/components/site-chrome';
import {languageAlternates} from '@/lib/seo';
import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {articles,getArticle,published,readingTime,wordCount} from '@/content/blog';
import {BlogContent,contents} from '@/components/blog-content';
import {DownloadActions} from '@/components/product-actions';
import {SITE,DEVELOPER} from '@/lib/product';
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return articles.map(({slug})=>({slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const a=getArticle((await params).slug);if(!a)return {title:'Статья не найдена — VCam',robots:{index:false,follow:true}};const image=`${SITE}/images/blog/${a.slug}.webp`;return {title:a.title+' — VCam',description:a.description,alternates:languageAlternates(`/blog/${a.slug}`),robots:{index:true,follow:true,'max-image-preview':'large'},openGraph:{type:'article',url:`/blog/${a.slug}`,title:a.title,description:a.description,publishedTime:published+'T00:00:00+07:00',modifiedTime:published+'T00:00:00+07:00',authors:[DEVELOPER],images:[{url:image,width:1600,height:900,alt:a.alt}]},twitter:{card:'summary_large_image',title:a.title,description:a.description,images:[image]}};}
export default async function ArticlePage({params}:Props){const a=getArticle((await params).slug);if(!a)notFound();const url=`${SITE}/blog/${a.slug}`;const schema={'@context':'https://schema.org','@graph':[{'@type':'BlogPosting','@id':url+'#article',headline:a.title,description:a.description,image:`${SITE}/images/blog/${a.slug}.webp`,datePublished:published+'T00:00:00+07:00',dateModified:published+'T00:00:00+07:00',author:{'@type':'Person',name:'EDDY',url:DEVELOPER},publisher:{'@type':'Organization',name:'VCam',url:SITE,logo:{'@type':'ImageObject',url:SITE+'/brand/icon-512.png'}},mainEntityOfPage:url,inLanguage:'ru',isAccessibleForFree:true,wordCount:wordCount(a.body),articleSection:a.category},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'VCam',item:SITE},{'@type':'ListItem',position:2,name:'Блог',item:SITE+'/blog'},{'@type':'ListItem',position:3,name:a.title,item:url}]}]};return <><SiteHeader path={`/blog/${a.slug}`}/><main id="main" className="article-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/><nav className="article-breadcrumb" aria-label="Хлебные крошки"><a href="/">VCam</a><span>/</span><a href="/blog">Блог</a><span>/</span><span>{a.category}</span></nav><header className="article-header"><span className="article-category">{a.category}</span><h1>{a.title}</h1><p>{a.description}</p><div className="article-meta"><a href={DEVELOPER}>EDDY · разработчик VCam</a><time dateTime={published}>28 сентября 2026</time><span>{readingTime(a.body)} мин чтения</span></div></header><figure className="article-cover"><img src={`/images/blog/${a.slug}.webp`} alt={a.alt} width="1600" height="900" fetchPriority="high"/><figcaption>Иллюстрация к статье</figcaption></figure><div className="article-layout"><aside className="article-toc"><details open><summary>В этой статье</summary><ol>{contents(a.body).map(h=><li key={h.id}><a href={`#${h.id}`}>{h.title}</a></li>)}</ol></details></aside><div><BlogContent body={a.body}/><section className="article-download"><img src="/brand/icon-64.png" width="48" height="48" alt=""/><h2>Попробовать VCam</h2><p>Бесплатно, без рекламы и водяного знака. Приложение нужно только на Windows; телефон подключается из браузера.</p><DownloadActions/><a className="article-connect" href="/connect">Сканировать QR или ввести код</a></section></div></div><section className="article-related"><h2>Читайте также</h2><div className="blog-grid">{a.related.map(slug=>{const related=getArticle(slug)!;return <article className="blog-card" key={slug}><a href={`/blog/${slug}`}><img src={`/images/blog/${slug}.webp`} alt={related.alt} width="1600" height="900" loading="lazy"/><div><h3>{related.title}</h3><span className="blog-read">{readingTime(related.body)} мин чтения ↗</span></div></a></article>})}</div></section></main><SiteFooter/></>}
